apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coder-demo
  region: us-east-1
  version: "1.30"

availabilityZones:
  - us-east-1a
  - us-east-1b

managedNodeGroups:
  - name: ng-coder
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 40
    privateNetworking: false
